#### Name: Md. Abid Ullah Muhib

#### Reg. No.: 2020331089

##### Session : 2020-2021

##### Computer Science & Engineering, SUST

<hr />


## Even Parity Error Detection for 4x8 Block

### Here's the step-by-step approach:

1. Generate a random 4x8 data block.
2. Calculate and append an even parity bit for each row.
3. Simulate a received data block with the parity bits.
4. Check for errors in the received data block.


In [4]:
import numpy as np

# Function to calculate even parity bit for a given row
def calculate_parity_bit(row):
    return 1 if np.sum(row) % 2 != 0 else 0

# Function to create a 4x8 data block with even parity bits
def create_data_block_with_parity():
    data_block = np.random.randint(0, 2, (4, 8))  # Generate a random 4x8 data block
    parity_block = np.zeros((4, 9), dtype=int)  # Initialize the parity block with an extra column for parity bit
    
    for i in range(4):
        parity_block[i, :8] = data_block[i]  # Copy the original data
        parity_block[i, 8] = calculate_parity_bit(data_block[i])  # Append the parity bit

    return parity_block

# Function to check for errors in the received data block with parity bits
def check_data_block_with_parity(parity_block):
    errors = []
    for i in range(4):
        row = parity_block[i, :8]  # Extract the original data row
        parity_bit = parity_block[i, 8]  # Extract the parity bit
        expected_parity = calculate_parity_bit(row)
        if parity_bit != expected_parity:
            errors.append(f"Error detected in row {i}")
    return errors

# Generate a 4x8 data block with even parity bits
data_block_with_parity = create_data_block_with_parity()

# Simulate a received data block (you can modify this to simulate errors)
received_data_block_with_parity = data_block_with_parity.copy()

# Introduce an error for testing (uncomment to introduce an error)
# received_data_block_with_parity[2, 3] = 1 - received_data_block_with_parity[2, 3]  # Flip a bit to simulate error

# Check for errors in the received data block
errors = check_data_block_with_parity(received_data_block_with_parity)

# Display results
print("Original Data Block with Parity Bits:")
print(data_block_with_parity)
print("\nReceived Data Block with Parity Bits:")
print(received_data_block_with_parity)

if errors:
    print("\nErrors detected:")
    for error in errors:
        print(error)
else:
    print("\nNo errors detected.")

Original Data Block with Parity Bits:
[[1 1 0 0 0 1 0 1 0]
 [0 1 1 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 1 0]
 [0 0 0 1 1 0 0 1 1]]

Received Data Block with Parity Bits:
[[1 1 0 0 0 1 0 1 0]
 [0 1 1 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 1 0]
 [0 0 0 1 1 0 0 1 1]]

No errors detected.
